// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

import (
	"time"
)

// PrimaryHeader defines model for PrimaryHeader.
type PrimaryHeader struct {
	PacketId      *int `json:"packetId,omitempty"`
	PacketLength  *int `json:"packetLength,omitempty"`
	PacketSeqCtrl *int `json:"packetSeqCtrl,omitempty"`
}

// SecondaryHeader defines model for SecondaryHeader.
type SecondaryHeader struct {
	SubsystemId *int       `json:"subsystemId,omitempty"`
	Timestamp   *time.Time `json:"timestamp,omitempty"`
}

// TelemetryPacket defines model for TelemetryPacket.
type TelemetryPacket struct {
	HasAnomaly      bool             `json:"hasAnomaly"`
	Payload         TelemetryPayload `json:"payload"`
	PrimaryHeader   PrimaryHeader    `json:"primaryHeader"`
	SecondaryHeader SecondaryHeader  `json:"secondaryHeader"`
}

// TelemetryPayload defines model for TelemetryPayload.
type TelemetryPayload struct {
	Altitude    float64 `json:"altitude"`
	Battery     float64 `json:"battery"`
	Signal      float64 `json:"signal"`
	Temperature float64 `json:"temperature"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// TelemetryDataListResponse defines model for TelemetryDataListResponse.
type TelemetryDataListResponse = []TelemetryPacket

// TelemetryDataResponse defines model for TelemetryDataResponse.
type TelemetryDataResponse = TelemetryPacket

// GetTelemetryParams defines parameters for GetTelemetry.
type GetTelemetryParams struct {
	// StartTime Start Time from where the data should be retrieved
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime End Time until where the data should be retrieved
	EndTime *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`
}

// GetTelemetryAnomaliesParams defines parameters for GetTelemetryAnomalies.
type GetTelemetryAnomaliesParams struct {
	// StartTime Start Time from where the data should be retrieved
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime End Time until where the data should be retrieved
	EndTime *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`
}
